openapi: 3.0.0
info:
  title: Minimum Spec
  version: 0.1.9
servers:
  - url: http://localhost
paths:
  /content:
    get:
      operationId: getContent
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentItemResponse'
components:
  schemas:
    ContentItemResponse:
      type: object
      discriminator:
        propertyName: contentType
      oneOf:
      - $ref: '#/components/schemas/File'
      - $ref: '#/components/schemas/Folder'
    CommonProperties:
      type: object
      properties:
        name:
          description: The name of the item.
          type: string
        readonly:
          description: Read only if true
          type: boolean
      required:
      - name
    Folder:
      allOf:
        - $ref: '#/components/schemas/CommonProperties'
        - type: object
          properties:
            contentType:
              description: Folder/File
              type: string
            children:
              description: Optional files and folders
              items:
                $ref: '#/components/schemas/ContentItemResponse'
              type: array
            color:
              description: contrived property for testing purposes
              type: string
          required:
            - color
            - contentType
    File:
      allOf:
        - $ref: '#/components/schemas/CommonProperties'
        - type: object
          properties:
            contentType:
              description: Folder/File
              type: string          
            fileType:
              type: string
          required:
            - contentType