openapi: 3.0.0
info:
  title: Minimum Spec
  version: 0.1.9
servers:
- url: http://localhost
paths:
  /content:
    get:
      operationId: getContent
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContentItemResponse'
          description: default response
components:
  schemas:
    ContentItemResponse:
      discriminator:
        propertyName: contentType
      oneOf:
      - $ref: '#/components/schemas/File'
      - $ref: '#/components/schemas/Folder'
      type: object
    CommonProperties:
      properties:
        name:
          description: The name of the item.
          type: string
        readonly:
          description: Read only if true
          type: boolean
      required:
      - name
      type: object
    Folder:
      allOf:
      - $ref: '#/components/schemas/CommonProperties'
      - properties:
          contentType:
            description: Folder/File
            type: string
          children:
            description: Optional files and folders
            items:
              $ref: '#/components/schemas/ContentItemResponse'
            type: array
          color:
            description: contrived property for testing purposes
            type: string
        required:
        - color
        - contentType
        type: object
    File:
      allOf:
      - $ref: '#/components/schemas/CommonProperties'
      - properties:
          contentType:
            description: Folder/File
            type: string
          fileType:
            type: string
        required:
        - contentType
        type: object
      example:
        readonly: true
        name: name
        contentType: contentType
        fileType: fileType
